services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: servicebooker
      POSTGRES_USER: servicebooker
      POSTGRES_PASSWORD: servicebooker_pw
    ports:
      - "5432:5432"
    volumes:
      - servicebooker_pg:/var/lib/postgresql/data

volumes:
  servicebooker_pg:

